# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_multi_label_R <- function(fname, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid) {
    .Call(`_readsparse_read_multi_label_R`, fname, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid)
}

read_multi_label_from_str_R <- function(file_as_str, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid) {
    .Call(`_readsparse_read_multi_label_from_str_R`, file_as_str, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid)
}

read_single_label_R <- function(fname, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid) {
    .Call(`_readsparse_read_single_label_R`, fname, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid)
}

read_single_label_from_str_R <- function(file_as_str, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid) {
    .Call(`_readsparse_read_single_label_from_str_R`, file_as_str, ignore_zero_valued, sort_indices, text_is_base1, assume_no_qid)
}

write_multi_label_R <- function(fname, indptr, indices, values, indptr_lab, indices_lab, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append) {
    .Call(`_readsparse_write_multi_label_R`, fname, indptr, indices, values, indptr_lab, indices_lab, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append)
}

write_multi_label_to_str_R <- function(indptr, indices, values, indptr_lab, indices_lab, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places) {
    .Call(`_readsparse_write_multi_label_to_str_R`, indptr, indices, values, indptr_lab, indices_lab, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places)
}

write_single_label_numeric_R <- function(fname, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append) {
    .Call(`_readsparse_write_single_label_numeric_R`, fname, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append)
}

write_single_label_integer_R <- function(fname, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append) {
    .Call(`_readsparse_write_single_label_integer_R`, fname, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places, append)
}

write_single_label_numeric_to_str_R <- function(indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places) {
    .Call(`_readsparse_write_single_label_numeric_to_str_R`, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places)
}

write_single_label_integer_to_str_R <- function(indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places) {
    .Call(`_readsparse_write_single_label_integer_to_str_R`, indptr, indices, values, labels, qid, ncols, nclasses, ignore_zero_valued, sort_indices, text_is_base1, add_header, decimal_places)
}

